import httpx
from app.config import settings

GITHUB_API = "https://api.github.com"

async def post_pr_comment(
    repo: str,
    pr_number: int,
    test_name: str,
    flakiness_score: float,
    root_cause: str,
    suggested_fix: str
):
    if not settings.github_token:
        print("No GitHub token configured, skipping PR comment")
        return

    score_percent = round(flakiness_score * 100)

    body = f"""## 🚨 Flaky Test Detected

| Field | Value |
|-------|-------|
| **Test** | `{test_name}` |
| **Flakiness Score** | {score_percent}% |
| **Root Cause** | {root_cause} |

### Analysis
This test has been detected as flaky by the automated test reliability system.

### Suggested Fix
{suggested_fix}

---
*Generated by Flaky Test Detector*
"""

    headers = {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    url = f"{GITHUB_API}/repos/{repo}/issues/{pr_number}/comments"

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url,
                json={"body": body},
                headers=headers,
                timeout=10.0
            )
            response.raise_for_status()
            print(f"GitHub PR comment posted on PR #{pr_number}")
    except Exception as e:
        print(f"Failed to post GitHub comment: {e}")


async def create_quarantine_issue(
    repo: str,
    test_name: str,
    root_cause: str,
    reasoning: str,
    suggested_fix: str
):
    if not settings.github_token:
        print("No GitHub token configured, skipping issue creation")
        return

    title = f"[Flaky Test] {test_name}"

    body = f"""## Flaky Test Report

**Test:** `{test_name}`
**Root Cause:** {root_cause}

### Analysis
{reasoning}

### Suggested Fix
{suggested_fix}

### Action Required
- [ ] Investigate the root cause
- [ ] Apply the suggested fix
- [ ] Verify the fix by running the test 10+ times
- [ ] Remove quarantine tag once fixed

---
*Auto-generated by Flaky Test Detector*
"""

    headers = {
        "Authorization": f"Bearer {settings.github_token}",
        "Accept": "application/vnd.github.v3+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    url = f"{GITHUB_API}/repos/{repo}/issues"

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url,
                json={
                    "title": title,
                    "body": body,
                    "labels": ["flaky-test", "bug"]
                },
                headers=headers,
                timeout=10.0
            )
            response.raise_for_status()
            data = response.json()
            print(f"GitHub issue created: {data.get('html_url')}")
            return data.get("html_url")
    except Exception as e:
        print(f"Failed to create GitHub issue: {e}")